# Generated by Django 5.2.14 on 2026-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradejournal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
