# Generated by Django 5.2.14 on 2026-06-03 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradejournal', '0002_rename_date_trade_entry_date_trade_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='contract_size',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Number of base currency units per standard lot', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Base to quote currency exchange rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='total_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total broker fees (commission + swap + spread)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='pip_size',
            field=models.DecimalField(decimal_places=5, help_text='Minimum price movement that represents one pip', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='leverage',
            field=models.PositiveIntegerField(blank=True, help_text='Amount of borrowed trading power', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trade volume in lots', max_digits=10, null=True),
        ),
    ]
